### ISSUE TITLE
xla_extension.so: cannot enable executable stack as shared object requires: Invalid argument

### ISSUE THREAD

**Issue by DSilva27** [jax-ml/jax#26781]
### Description

I got this bug today after creating a fresh environment. I tried creating the env using uv and venv, and it happened in both cases. The bug happened in both python 3.11.11 and 3.13.1 (did not check more). Here is the full error message

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/my/env/myenv_name/lib/python3.11/site-packages/jax/__init__.py", line 25, in <module>
    from jax._src.cloud_tpu_init import cloud_tpu_init as _cloud_tpu_init
  File "/path/to/my/env/myenv_name/lib/python3.11/site-packages/jax/_src/cloud_tpu_init.py", line 19, in <module>
    from jax._src import config
  File "/path/to/my/env/myenv_name/lib/python3.11/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src.lib import guard_lib
  File "/path/to/my/env/myenv_name/lib/python3.11/site-packages/jax/_src/lib/__init__.py", line 87, in <module>
    import jaxlib.xla_client as xla_client
  File "/path/to/my/env/myenv_name/lib/python3.11/site-packages/jaxlib/xla_client.py", line 33, in <module>
    from . import xla_extension as _xla
ImportError: /path/to/my/env/myenv_name/lib/python3.11/site-packages/jaxlib/xla_extension.so: cannot enable executable stack as shared object requires: Invalid argument

```

I managed to fix this by running  `execstack -c /path/to/my/env/myenv_name/lib/python3.11/site-packages/jaxlib/xla_extension.so`. 

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.5.1
jaxlib: 0.5.1
numpy:  2.2.3
python: 3.11.11 (main, Feb 12 2025, 14:51:05) [Clang 19.1.6 ]
device info: cpu-1, 1 local devices"
process_count: 1
platform: uname_result(system='Linux', node='asusvivobook', release='6.6.75-2-MANJARO', version='#1 SMP PREEMPT_DYNAMIC Mon Feb  3 17:53:46 UTC 2025', machine='x86_64')
```

**Comment by nshepperd** [comment]
This seems to be a regression in jaxlib 0.5.1. The xla_extension.so indeed has the stack marked as executable:
```
$ objdump -x .venv/lib/python3.12/site-packages/jaxlib/xla_extension.so | grep -A1 'STACK off'
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rwx
```
While jaxlib 0.5.0 does not:
```
$ objdump -x .venv/lib/python3.12/site-packages/jaxlib/xla_extension.so | grep -A1 'STACK off'
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
```
An unhappy coincidence given that dlopen'ing executable stacks was officially removed from glibc less than a month ago, in version 2.41!

**Comment by nshepperd** [comment]
Also, this might actually be an XLA issue, since xla_extension.so comes from XLA. But I can't to be sure, because I couldn't reproduce the issue with xla_extension.so compiling XLA by itself under some configurations, and couldn't get the compilation to work at all under other configurations. So this may also be an issue with the compilation environment of jaxlib's wheels specifically.

**Comment by sandycat27** [comment]
I have the same issue. Reverting to jax version 0.5.0 cleared the issue.

**Comment by ybaturina** [comment]
The fix was merged in https://github.com/openxla/xla/pull/23266.

**Comment by hawkinsp** [comment]
Can one of the reporters please confirm this is fixed in tomorrow's JAX nightly? Thanks!

**Comment by DSilva27** [comment]
> Can one of the reporters please confirm this is fixed in tomorrow's JAX nightly? Thanks!

I'd be happy to do it, but I don't know what this means.

**Comment by hawkinsp** [comment]
> > Can one of the reporters please confirm this is fixed in tomorrow's JAX nightly? Thanks!
> 
> I'd be happy to do it, but I don't know what this means.

I mean: install the latest nightly build of JAX, and verify that the problem is no longer present (https://docs.jax.dev/en/latest/installation.html#jax-nightly-installation)

**Comment by roth-jakob** [comment]
For the CPU-only installation, I can verify that the issue is solved for me. I cannot test the CUDA installations.

**Comment by hawkinsp** [comment]
Awesome! I guess I'll leave this issue closed, then. The next release should be around March 15 or shortly thereafter.

**Comment by DSilva27** [comment]
I also confirm that the issue is fixed.

**Comment by carlosal1015** [comment]
![Image](https://github.com/user-attachments/assets/d6c7ce5b-8070-4288-a971-b170436bf5db)

**Comment by jacanchaplais** [comment]
Issue not fixed for me. I installed via conda, with the following packages

```
List of packages in environment: "/home/jacan/.micromamba/envs/tesseract"

  Name                           Version         Build                     Channel
────────────────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex                  0.1             conda_forge               conda-forge
  _openmp_mutex                  4.5             2_gnu                     conda-forge
  anyio                          4.9.0           pyh29332c3_0              conda-forge
  argon2-cffi                    23.1.0          pyhd8ed1ab_1              conda-forge
  argon2-cffi-bindings           21.2.0          py312h66e93f0_5           conda-forge
  arrow                          1.3.0           pyhd8ed1ab_1              conda-forge
  asttokens                      3.0.0           pyhd8ed1ab_1              conda-forge
  async-lru                      2.0.5           pyh29332c3_0              conda-forge
  attrs                          25.3.0          pyh71513ae_0              conda-forge
  babel                          2.17.0          pyhd8ed1ab_0              conda-forge
  beautifulsoup4                 4.13.3          pyha770c72_0              conda-forge
  bleach                         6.2.0           pyh29332c3_4              conda-forge
  bleach-with-css                6.2.0           h82add2a_4                conda-forge
  brotli-python                  1.1.0           py312h2ec8cdc_2           conda-forge
  bzip2                          1.0.8           h4bc722e_7                conda-forge
  c-ares                         1.34.4          hb9d3cd8_0                conda-forge
  ca-certificates                2025.1.31       hbcca054_0                conda-forge
  cached-property                1.5.2           hd8ed1ab_1                conda-forge
  cached_property                1.5.2           pyha770c72_1              conda-forge
  certifi                        2025.1.31       pyhd8ed1ab_0              conda-forge
  cffi                           1.17.1          py312h06ac9bb_0           conda-forge
  charset-normalizer             3.4.1           pyhd8ed1ab_0              conda-forge
  click                          8.1.8           pyh707e725_0              conda-forge
  colorama                       0.4.6           pyhd8ed1ab_1              conda-forge
  comm                           0.2.2           pyhd8ed1ab_1              conda-forge
  cuda-cccl_linux-64             12.8.90         ha770c72_1                conda-forge
  cuda-crt-dev_linux-64          12.8.93         ha770c72_1                conda-forge
  cuda-crt-tools                 12.8.93         ha770c72_1                conda-forge
  cuda-cudart                    12.8.90         h5888daf_1                conda-forge
  cuda-cudart-dev_linux-64       12.8.90         h3f2d84a_1                conda-forge
  cuda-cudart-static_linux-64    12.8.90         h3f2d84a_1                conda-forge
  cuda-cudart_linux-64           12.8.90         h3f2d84a_1                conda-forge
  cuda-cupti                     12.8.90         hbd13f7d_0                conda-forge
  cuda-cupti-dev                 12.8.90         h5888daf_0                conda-forge
  cuda-nvcc-tools                12.8.93         he02047a_1                conda-forge
  cuda-nvrtc                     12.8.93         h5888daf_1                conda-forge
  cuda-nvtx                      12.8.90         hbd13f7d_0                conda-forge
  cuda-nvvm-tools                12.8.93         he02047a_1                conda-forge
  cuda-version                   12.8            h5d125a7_3                conda-forge
  cudnn                          9.8.0.87        h81d5506_0                conda-forge
  debugpy                        1.8.13          py312h2ec8cdc_0           conda-forge
  decorator                      5.2.1           pyhd8ed1ab_0              conda-forge
  defusedxml                     0.7.1           pyhd8ed1ab_0              conda-forge
  exceptiongroup                 1.2.2           pyhd8ed1ab_1              conda-forge
  executing                      2.1.0           pyhd8ed1ab_1              conda-forge
  fqdn                           1.5.1           pyhd8ed1ab_1              conda-forge
  h11                            0.14.0          pyhd8ed1ab_1              conda-forge
  h2                             4.2.0           pyhd8ed1ab_0              conda-forge
  hpack                          4.1.0           pyhd8ed1ab_0              conda-forge
  httpcore                       1.0.7           pyh29332c3_1              conda-forge
  httpx                          0.28.1          pyhd8ed1ab_0              conda-forge
  hyperframe                     6.1.0           pyhd8ed1ab_0              conda-forge
  icu                            75.1            he02047a_0                conda-forge
  idna                           3.10            pyhd8ed1ab_1              conda-forge
  importlib-metadata             8.6.1           pyha770c72_0              conda-forge
  importlib_resources            6.5.2           pyhd8ed1ab_0              conda-forge
  ipdb                           0.13.13         pyhd8ed1ab_1              conda-forge
  ipykernel                      6.29.5          pyh3099207_0              conda-forge
  ipython                        9.0.2           pyhfb0248b_0              conda-forge
  ipython_pygments_lexers        1.1.1           pyhd8ed1ab_0              conda-forge
  isoduration                    20.11.0         pyhd8ed1ab_1              conda-forge
  jax                            0.5.2           pyhd8ed1ab_0              conda-forge
  jaxlib                         0.5.2           cuda126py312hbc630d6_201  conda-forge
  jedi                           0.19.2          pyhd8ed1ab_1              conda-forge
  jinja2                         3.1.6           pyhd8ed1ab_0              conda-forge
  json5                          0.10.0          pyhd8ed1ab_1              conda-forge
  jsonpointer                    3.0.0           py312h7900ff3_1           conda-forge
  jsonschema                     4.23.0          pyhd8ed1ab_1              conda-forge
  jsonschema-specifications      2024.10.1       pyhd8ed1ab_1              conda-forge
  jsonschema-with-format-nongpl  4.23.0          hd8ed1ab_1                conda-forge
  jupyter-lsp                    2.2.5           pyhd8ed1ab_1              conda-forge
  jupyter_client                 8.6.3           pyhd8ed1ab_1              conda-forge
  jupyter_core                   5.7.2           pyh31011fe_1              conda-forge
  jupyter_events                 0.12.0          pyh29332c3_0              conda-forge
  jupyter_server                 2.15.0          pyhd8ed1ab_0              conda-forge
  jupyter_server_terminals       0.5.3           pyhd8ed1ab_1              conda-forge
  jupyterlab                     4.3.6           pyhd8ed1ab_0              conda-forge
  jupyterlab-lsp                 5.1.0           pyhd8ed1ab_3              conda-forge
  jupyterlab_pygments            0.3.0           pyhd8ed1ab_2              conda-forge
  jupyterlab_server              2.27.3          pyhd8ed1ab_1              conda-forge
  jupyterlab_vim                 4.1.4           pyhd8ed1ab_1              conda-forge
  keyutils                       1.6.1           h166bdaf_0                conda-forge
  krb5                           1.21.3          h659f571_0                conda-forge
  ld_impl_linux-64               2.43            h712a8e2_4                conda-forge
  libabseil                      20250127.1      cxx17_hbbce691_0          conda-forge
  libblas                        3.9.0           31_h59b9bed_openblas      conda-forge
  libcblas                       3.9.0           31_he106b2a_openblas      conda-forge
  libcublas                      12.8.4.1        h9ab20c4_1                conda-forge
  libcublas-dev                  12.8.4.1        h9ab20c4_1                conda-forge
  libcufft                       11.3.3.83       h5888daf_1                conda-forge
  libcufft-dev                   11.3.3.83       h5888daf_1                conda-forge
  libcurand                      10.3.9.90       hbd13f7d_0                conda-forge
  libcurand-dev                  10.3.9.90       h5888daf_0                conda-forge
  libcusolver                    11.7.3.90       h9ab20c4_1                conda-forge
  libcusolver-dev                11.7.3.90       h9ab20c4_1                conda-forge
  libcusparse                    12.5.8.93       hbd13f7d_0                conda-forge
  libcusparse-dev                12.5.8.93       h5888daf_0                conda-forge
  libedit                        3.1.20250104    pl5321h7949ede_0          conda-forge
  libexpat                       2.6.4           h5888daf_0                conda-forge
  libffi                         3.4.6           h2dba641_0                conda-forge
  libgcc                         14.2.0          h767d61c_2                conda-forge
  libgcc-ng                      14.2.0          h69a702a_2                conda-forge
  libgfortran                    14.2.0          h69a702a_2                conda-forge
  libgfortran5                   14.2.0          hf1ad2bd_2                conda-forge
  libgomp                        14.2.0          h767d61c_2                conda-forge
  libgrpc                        1.71.0          he753a82_0                conda-forge
  libiconv                       1.18            h4ce23a2_1                conda-forge
  liblapack                      3.9.0           31_h7ac8fdf_openblas      conda-forge
  libllvm15                      15.0.7          ha7bfdaf_5                conda-forge
  liblzma                        5.6.4           hb9d3cd8_0                conda-forge
  libnsl                         2.0.1           hd590300_0                conda-forge
  libnvjitlink                   12.8.93         h5888daf_1                conda-forge
  libopenblas                    0.3.29          pthreads_h94d23a6_0       conda-forge
  libprotobuf                    5.29.3          h501fc15_0                conda-forge
  libre2-11                      2024.07.02      hba17884_3                conda-forge
  libsodium                      1.0.20          h4ab18f5_0                conda-forge
  libsqlite                      3.49.1          hee588c1_2                conda-forge
  libstdcxx                      14.2.0          h8f9b012_2                conda-forge
  libstdcxx-ng                   14.2.0          h4852527_2                conda-forge
  libuuid                        2.38.1          h0b41bf4_0                conda-forge
  libxcrypt                      4.4.36          hd590300_1                conda-forge
  libxml2                        2.13.6          h8d12d68_0                conda-forge
  libzlib                        1.3.1           hb9d3cd8_2                conda-forge
  llvmlite                       0.44.0          py312h374181b_0           conda-forge
  markupsafe                     3.0.2           py312h178313f_1           conda-forge
  matplotlib-inline              0.1.7           pyhd8ed1ab_1              conda-forge
  mistune                        3.1.3           pyh29332c3_0              conda-forge
  ml_dtypes                      0.5.1           py312hf9745cd_0           conda-forge
  narwhals                       1.31.0          pyhd8ed1ab_0              conda-forge
  nbclient                       0.10.2          pyhd8ed1ab_0              conda-forge
  nbconvert-core                 7.16.6          pyh29332c3_0              conda-forge
  nbformat                       5.10.4          pyhd8ed1ab_1              conda-forge
  nccl                           2.26.2.1        ha44e49d_0                conda-forge
  ncurses                        6.5             h2d0b736_3                conda-forge
  nest-asyncio                   1.6.0           pyhd8ed1ab_1              conda-forge
  notebook-shim                  0.2.4           pyhd8ed1ab_1              conda-forge
  numba                          0.61.0          py312h2e6246c_1           conda-forge
  numpy                          2.1.3           py312h58c1407_0           conda-forge
  openssl                        3.4.1           h7b32b05_0                conda-forge
  opt_einsum                     3.4.0           pyhd8ed1ab_1              conda-forge
  overrides                      7.7.0           pyhd8ed1ab_1              conda-forge
  packaging                      24.2            pyhd8ed1ab_2              conda-forge
  pandas                         2.2.3           py312hf9745cd_1           conda-forge
  pandocfilters                  1.5.0           pyhd8ed1ab_0              conda-forge
  parso                          0.8.4           pyhd8ed1ab_1              conda-forge
  pexpect                        4.9.0           pyhd8ed1ab_1              conda-forge
  pickleshare                    0.7.5           pyhd8ed1ab_1004           conda-forge
  pip                            25.0.1          pyh8b19718_0              conda-forge
  pkgutil-resolve-name           1.3.10          pyhd8ed1ab_2              conda-forge
  platformdirs                   4.3.6           pyhd8ed1ab_1              conda-forge
  plotly                         6.0.1           pyhd8ed1ab_0              conda-forge
  prometheus_client              0.21.1          pyhd8ed1ab_0              conda-forge
  prompt-toolkit                 3.0.50          pyha770c72_0              conda-forge
  psutil                         7.0.0           py312h66e93f0_0           conda-forge
  ptyprocess                     0.7.0           pyhd8ed1ab_1              conda-forge
  pure_eval                      0.2.3           pyhd8ed1ab_1              conda-forge
  pycparser                      2.22            pyh29332c3_1              conda-forge
  pygments                       2.19.1          pyhd8ed1ab_0              conda-forge
  pysocks                        1.7.1           pyha55dd90_7              conda-forge
  python                         3.12.9          h9e4cc4f_1_cpython        conda-forge
  python-dateutil                2.9.0.post0     pyhff2d567_1              conda-forge
  python-fastjsonschema          2.21.1          pyhd8ed1ab_0              conda-forge
  python-json-logger             2.0.7           pyhd8ed1ab_0              conda-forge
  python-tzdata                  2025.1          pyhd8ed1ab_0              conda-forge
  python_abi                     3.12            5_cp312                   conda-forge
  pytz                           2024.1          pyhd8ed1ab_0              conda-forge
  pyyaml                         6.0.2           py312h178313f_2           conda-forge
  pyzmq                          26.3.0          py312hbf22597_0           conda-forge
  re2                            2024.07.02      h9925aae_3                conda-forge
  readline                       8.2             h8c095d6_2                conda-forge
  referencing                    0.36.2          pyh29332c3_0              conda-forge
  requests                       2.32.3          pyhd8ed1ab_1              conda-forge
  rfc3339-validator              0.1.4           pyhd8ed1ab_1              conda-forge
  rfc3986-validator              0.1.1           pyh9f0ad1d_0              conda-forge
  rpds-py                        0.23.1          py312h3b7be25_0           conda-forge
  scipy                          1.15.2          py312ha707e6e_0           conda-forge
  send2trash                     1.8.3           pyh0d859eb_1              conda-forge
  setuptools                     75.8.2          pyhff2d567_0              conda-forge
  six                            1.17.0          pyhd8ed1ab_0              conda-forge
  sniffio                        1.3.1           pyhd8ed1ab_1              conda-forge
  soupsieve                      2.5             pyhd8ed1ab_1              conda-forge
  stack_data                     0.6.3           pyhd8ed1ab_1              conda-forge
  terminado                      0.18.1          pyh0d859eb_0              conda-forge
  tesseract-core                 0.7.3           pypi_0                    pypi
  tinycss2                       1.4.0           pyhd8ed1ab_0              conda-forge
  tk                             8.6.13          noxft_h4845f30_101        conda-forge
  toml                           0.10.2          pyhd8ed1ab_1              conda-forge
  tomli                          2.2.1           pyhd8ed1ab_1              conda-forge
  tornado                        6.4.2           py312h66e93f0_0           conda-forge
  tqdm                           4.67.1          pyhd8ed1ab_1              conda-forge
  traitlets                      5.14.3          pyhd8ed1ab_1              conda-forge
  types-python-dateutil          2.9.0.20241206  pyhd8ed1ab_0              conda-forge
  typing-extensions              4.12.2          hd8ed1ab_1                conda-forge
  typing_extensions              4.12.2          pyha770c72_1              conda-forge
  typing_utils                   0.1.0           pyhd8ed1ab_1              conda-forge
  tzdata                         2025a           h78e105d_0                conda-forge
  uri-template                   1.3.0           pyhd8ed1ab_1              conda-forge
  urllib3                        2.3.0           pyhd8ed1ab_0              conda-forge
  wcwidth                        0.2.13          pyhd8ed1ab_1              conda-forge
  webcolors                      24.11.1         pyhd8ed1ab_0              conda-forge
  webencodings                   0.5.1           pyhd8ed1ab_3              conda-forge
  websocket-client               1.8.0           pyhd8ed1ab_1              conda-forge
  wheel                          0.45.1          pyhd8ed1ab_1              conda-forge
  yaml                           0.2.5           h7f98852_2                conda-forge
  zeromq                         4.3.5           h3b0a872_7                conda-forge
  zipp                           3.21.0          pyhd8ed1ab_1              conda-forge
  zstandard                      0.23.0          py312h66e93f0_1           conda-forge
  zstd                           1.5.7           hb8e6e7a_2                conda-forge
```

on Arch Linux

```
❯ fastfetch
                  -`                     jacan@pasteur
                 .o+`                    -------------
                `ooo/                    OS: Arch Linux x86_64
               `+oooo:                   Host: 20Y5007GUS (ThinkPad X1 Extreme Gen 4i)
              `+oooooo:                  Kernel: Linux 6.13.7-arch1-1
              -+oooooo+:                 Uptime: 2 hours, 54 mins
            `/:-:++oooo+:                Packages: 1138 (pacman)
           `/++++/+++++++:               Shell: zsh 5.9
          `/++++++++++++++:              Display (LGD06AA): 3840x2400 @ 60 Hz in 16" [External]
         `/+++ooooooooooooo/`            WM: bspwm (X11)
        ./ooosssso++osssssso+`           Theme: Arc-Dark [GTK2/3]
       .oossssso-````/ossssss+`          Icons: Adwaita [GTK2/3]
      -osssssso.      :ssssssso.         Font: Cantarell (11pt) [GTK2/3]
     :osssssss/        osssso+++.        Cursor: Adwaita
    /ossssssss/        +ssssooo/-        Terminal: tmux 3.5a
  `/ossssso+/:-        -:/+osssso+-      CPU: 11th Gen Intel(R) Core(TM) i7-11850H (16) @ 4.80 GHz
 `+sso+:-`                 `.-/+oso:     GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q [Discrete]
`++:.                           `-/+/    Memory: 6.30 GiB / 15.40 GiB (41%)
.`                                 `/    Swap: Disabled
                                         Disk (/): 39.68 GiB / 953.35 GiB (4%) - btrfs
                                         Local IP (wlp9s0): 192.168.0.122/24
                                         Battery (5B11B79217): 97% [AC Connected]
                                         Locale: en_GB.UTF-8
```

and still get the error.

**Comment by jacanchaplais** [comment]
Ah thanks @hawkinsp, I just assumed since the version numbers were the same, it would be fixed regardless of the distributor. I've added it to my PyPI requirements instead of from conda-forge. :)

**Comment by hawkinsp** [comment]
I do suspect the next conda-forge release may fix the problem there also, but they haven't made the necessary release yet...
