### ISSUE TITLE
MacOS: Some `mujoco.mjx` models are >100x slower on `jax>=0.7` than on `jax<0.7`

### ISSUE THREAD

**Issue by hartikainen** [jax-ml/jax#33761]
### Description

I originally posted this in https://github.com/google-deepmind/mujoco/issues/2957. TLDR: Some of our [`mujoco.mjx`](https://github.com/google-deepmind/mujoco/tree/main/mjx) models are running >100x slower on MacOS when using `jax>=0.7`, compared to `jax<0.7`.

Here's the reproduction script from https://github.com/google-deepmind/mujoco/issues/2957:

<details><summary>`slow_jax.py`</summary>

```python
import time
import jax
import mujoco
from mujoco import mjx
import numpy as np

# Create a chain of bodies with many geoms and sites
xml = "<mujoco>\n"
xml += "  <worldbody>\n"
xml += '    <body name="0" pos="0 0 0">\n'
xml += '      <joint type="free"/>\n'
xml += '      <geom size="0.1"/>\n'

depth = 9  # > 20 joints
geoms_per_body = 1
sites_per_body = 1

for i in range(1, depth):
    xml += f'      <body name="{i}" pos="0.1 0 0">\n'
    xml += '        <joint type="hinge"/>\n'
    xml += '        <geom size="0.1"/>\n'
    for j in range(geoms_per_body):
        xml += f'        <geom size="0.01" pos="0 {j*0.01} 0"/>\n'
    for j in range(sites_per_body):
        xml += f'        <site name="s_{i}_{j}" pos="0 0 {j*0.01}"/>\n'

for i in range(depth):
    xml += "    </body>"

xml += "\n  </worldbody>\n"
xml += "</mujoco>\n"

m = mujoco.MjModel.from_xml_string(xml)
d = mujoco.MjData(m)
mx = mjx.put_model(m)
dx = mjx.put_data(m, d)

print(f"Running benchmark with {depth} bodies, {m.ngeom} geoms, {m.nsite} sites on {jax.default_backend()}")

# Compile
kinematics_jit = jax.jit(mjx.kinematics)
dx = kinematics_jit(mx, dx)
dx.qpos.block_until_ready()
print("Compiled.")

# Benchmark
start = time.time()
N = 3
for _ in range(N):
    dx = kinematics_jit(mx, dx)
    dx.qpos.block_until_ready()
end = time.time()

print(f"Time for {N} iterations: {end - start:.4f}s")
print(f"Avg time: {(end - start)/N*1000:.4f}ms")
```

</details>

When I run this, I get
```console
$ uv pip list | grep "jax\|mjx\|mujoco"
jax                 0.6.2
jaxlib              0.6.2
mujoco              3.3.7
mujoco-mjx          3.3.7
$ python ./slow_jax.py
Running benchmark with 9 bodies, 17 geoms, 8 sites on cpu
Compiled.
Time for 100 iterations: 0.0178s
Avg time: 0.1784ms
$ uv pip install -U "jax"
Resolved 6 packages in 110ms
Prepared 2 packages in 0.17ms
Uninstalled 2 packages in 51ms
Installed 2 packages in 7ms
 - jax==0.6.2
 + jax==0.8.1
 - jaxlib==0.6.2
 + jaxlib==0.8.1
$ python ./slow_jax.py
Running benchmark with 9 bodies, 17 geoms, 8 sites on cpu
Compiled.
Time for 100 iterations: 40.7880s
Avg time: 407.8800ms
```

### System info (python version, jaxlib version, accelerator, etc.)

```console
python -c "import jax; jax.print_environment_info()"
jax:    0.8.1
jaxlib: 0.8.1
numpy:  2.3.5
python: 3.12.11 (main, Jun  9 2025, 18:04:24) [Clang 20.1.4 ]
device info: cpu-1, 1 local devices"
process_count: 1
platform: uname_result(system='Darwin', node='MacBook-Pro.local', release='24.6.0', version='Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:40 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6041', machine='arm64')
```

**Comment by rdyro** [comment]
I can reproduce this on a linux laptop and can confirm this isn't related to re-compilation, the actual execution appears to be taking much longer now.

I'll take a look at bisecting it to a specific commit, thanks for the repro!

Could this dynamics problem be borderline stiff, so that small numerical differences are triggering vastly different number of integration steps?

**Comment by hartikainen** [comment]
Thanks @rdyro. If I understand correctly, the variable number of integration steps wouldn't be a problem here because `mjx` executes everything statically. Perhaps @btaba can confirm if my understanding is right.

**Comment by btaba** [comment]
+1 the solver iterations are fixed for pure JAX implementations of MuJoCo. You should probably set the solver iterations in your MJCF explicitly

**Comment by rdyro** [comment]
This seems to be caused by the new XLA:CPU fusion emitters, you can get the old behavior by disabling them:

```
XLA_FLAGS="--xla_backend_extra_options=xla_cpu_disable_new_fusion_emitters=true"
```

**Comment by hartikainen** [comment]
I can verify that the above `--xla_backend_extra_options=xla_cpu_disable_new_fusion_emitters=true` flag fixes the slowness, both with my original reproduction code but also with our actual model. Thanks @rdyro!

**Comment by rdyro** [comment]
I reported this internally with the compiler team, they're looking into a potential fix.

**Comment by btaba** [comment]
Thanks @rdyro for being on top of this, really appreciate it!

**Comment by btaba** [comment]
@hartikainen @rdyro is this issue fixed by any chance?

**Comment by hartikainen** [comment]
Just tested this on `jax==0.9.1` and the problem still persists unless I explicitly disable the fusion emitters mentioned above.

**Comment by btaba** [comment]
Thanks @hartikainen , @rdyro any updates on your end?

**Comment by rdyro** [comment]
This is due to the new XLA:CPU fusions, I followed up on this internally with the compiler team, but it'd probably be a good idea to track it in https://github.com/openxla/xla

**Comment by epokhcs** [comment]
Also for reference older version:

```
Using Python 3.12.12 environment at: venv
jax               0.5.0
jax-metal         0.1.1
jaxlib            0.5.0
mujoco            3.6.0
mujoco-mjx        3.6.0    /Users/pdiprodi/DevOps/github/mujoco/mjx

Time for 3 iterations: 0.0244s
Avg time: 8.1383ms
```

**Comment by epokhcs** [comment]
@hartikainen I can confirm performance is restored when updating to the latest version and using the XLA_FLAGS="--xla_backend_extra_options=xla_cpu_disable_new_fusion_emitters=true" fix.

**Comment by hartikainen** [comment]
This is fixed, at least in `jax==0.11.1`. See https://github.com/google-deepmind/mujoco/issues/2957#issuecomment-5398589111. Thanks for the fix!
